[tool.poetry]
name = "repl_python3_beta_yukiyo"
version = "0.1.0"
description = ""
authors = ["Ehnryu <<>>"]



[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
